Update binder.c for compatibility with kernel 5.3
anbox/anbox-modules pull request #36
Opened 2019-10-22 04:16 UTC by SoulInfernoDE

fixes error while compiling binder with kernel versions 5.3

/var/lib/dkms/anbox/1/build/binder/binder.c:3406:11: error: initialization of ‘vm_fault_t (*)(struct vm_fault *)’ {aka ‘unsigned int (*)(struct vm_fault *)’} from incompatible pointer type ‘int (*)(struct vm_fault
 *)’ [-Werror=incompatible-pointer-types]
  .fault = binder_vm_fault,
           ^~~~~~~~~~~~~~~
/var/lib/dkms/anbox/1/build/binder/binder.c:3406:11: note: (near initialization for ‘binder_vm_ops.fault’)
cc1: some warnings being treated as errors

:+1:  fixed :+1:

2019-12-15 16:04 UTC, morphis requested changes

2019-12-15 16:04 UTC, morphis commented on binder/binder.c
> +#if LINUX_VERSION_CODE >= KERNEL_VERSION(5, 3, 0)
The signature is different in 5.1 and 5.2 still. In order to support both we have to define the signature of both versions here too and add a proper if around them.

2020-01-17 13:26 UTC, mikma commented on binder/binder.c
> +#if LINUX_VERSION_CODE >= KERNEL_VERSION(5, 3, 0)
To me it seems like the `vm_fault_t (*fault)(struct vm_fault *vmf);` signature was changed in kernel 4.17, and hasn't been changed after that, in mainline at least.
https://github.com/torvalds/linux/commit/1c8f422059ae5da07db7406ab916203f9417e396
With the following patch to anbox-modules-dkms version 13 the module builds in both 5.1.15 and 5.4.12 for me.

--- binder/binder.c.orig	2020-01-17 14:08:56.306373591 +0100
+++ binder/binder.c	2020-01-17 14:09:23.078508434 +0100
@@ -3367,7 +3367,9 @@
 	binder_defer_work(proc, BINDER_DEFERRED_PUT_FILES);
 }
 
-#if LINUX_VERSION_CODE >= KERNEL_VERSION(4, 11, 0)
+#if LINUX_VERSION_CODE >= KERNEL_VERSION(4, 17, 0)
+static vm_fault_t binder_vm_fault(struct vm_fault *vmf)
+#elif LINUX_VERSION_CODE >= KERNEL_VERSION(4, 11, 0)
 static int binder_vm_fault(struct vm_fault *vmf)
 #else
 static int binder_vm_fault(struct vm_area_struct *vma, struct vm_fault *vmf)

2020-03-28 16:20 UTC, TheOneWithTheBraid commented
Could you try out https://gitlab.com/gobudgie/anbox-modules/-/tree/linux54 ?

2025-07-23 00:36 UTC, closed without merging